spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rebenbot
    driver-class-name: org.postgresql.Driver
    username: rebenbot
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    org.flywaydb: INFO
